const sidebars = {
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  docs: [
    {
      id: 'intro',
      type: 'doc'
    },
    {
      id: 'what-is-onenine-cloud',
      type: 'doc',
    },
    {
      label: 'Data Literacy',
      type: 'category',
      items: [
        'data-literacy/data-literacy-intro',
        'data-literacy/start-data-science-journey'
      ]
    },
    {
      label: 'Data Analysis',
      type: 'category',
      items: [
        'data-analysis/data-analysis-intro',
        'data-analysis/one-click-data-analysis',
        'data-analysis/advanced-data-analysis',
      ]
    },
    {
      label: 'Data Visualization',
      type: 'category',
      items: [
        'data-visualisation/data-visualisation-intro',
        'data-visualisation/data-visualisation-types',
        'data-visualisation/creating-charts',
        'data-visualisation/creating-dashboards',
        'data-visualisation/data-visualisation-examples',
      ]
    },
    {
      label: 'AI Projects',
      type: 'category',
      items: [
        'ai-projects/ai-projects-intro',
        'ai-projects/ml-model-types',
        'ai-projects/ai-projects-examples',
      ]
    },
    {
      label: 'Discovery Projects',
      type: 'category',
      items: [
        'discovery-projects/discovery-projects-intro',
        'discovery-projects/deep-learning-model-types',
        'discovery-projects/discovery-projects-examples',
      ]
    },
    {
      label: 'Smart Models',
      type: 'category',
      items: [
        'smart-models/smart-models-intro',
        'smart-models/use-case-driven-models',
        'smart-models/smart-models-examples',
      ]
    },
    {
      label: 'Open Source Data Search',
      type: 'category',
      items: [
        'open-source-data-search/open-source-data-search-intro',
        'open-source-data-search/open-source-data-search-repos',
        'open-source-data-search/open-source-data-search-examples',
      ]
    },
    {
      label: 'Real Time Predictions',
      type: 'category',
      items: [
        'realtime-predictions/realtime-prediction-intro',
        'realtime-predictions/how-to-setup-real-time-predicitons',
        'realtime-predictions/realtime-prediction-examples',
      ]
    },
    {
      label: 'Organising Projects',
      type: 'category',
      items: [
        'organising-projects/organising-projects-intro',
        'organising-projects/how-to-organise-projects',
        'organising-projects/organising-projects-examples',
      ]
    },
    {
      label: 'FAQ',
      id: 'faq',
      type: 'doc',
    },
  ],

  // Tutorials Sidebar
  TutorialSidebar: [
    {
      id: "tutorials-page",
      type: "doc",
    },
  ]
};

module.exports = sidebars;
